### ISSUE TITLE
redis的配置类和配置文件能否也增加上来？

### ISSUE THREAD

**Issue by leechaun** [vvsuperman/coolmq#2]
redis的配置类和配置文件好像没有提交到代码中。

**Comment by vvsuperman** [comment]
收到

**Comment by wfm0105** [comment]
我自己实现了redis 操作，现在遇到一个问题，就是
public class RabbitMetaMessage{
	private static final long serialVersionUID = -1L;
	String exchange;
	String routingKey;
	boolean autoTrigger;
	boolean returnCallback;
	Object payload;
	
	public Object getPayload() {
		return payload;
	}
	public void setPayload(Object payload) {
		this.payload = payload;
	}
	public boolean isReturnCallback() {
		return returnCallback;
	}
	public void setReturnCallback(boolean returnCallback) {
		this.returnCallback = returnCallback;
	}
	public String getExchange() {
		return exchange;
	}
	public void setExchange(String exchange) {
		this.exchange = exchange;
	}
	public String getRoutingKey() {
		return routingKey;
	}
	public void setRoutingKey(String routingKey) {
		this.routingKey = routingKey;
	}
	public boolean isAutoTrigger() {
		return autoTrigger;
	}
	public void setAutoTrigger(boolean autoTrigger) {
		this.autoTrigger = autoTrigger;
	}




}

这个类的Object 无法序列化
出现下面异常，请教下这个改怎么处理

org.springframework.data.redis.serializer.SerializationException: Could not write JSON: Type id handling not implemented for type java.lang.String (by serializer of type com.zxymq.amqp.util.json.JsonMapper$2) (through reference chain: com.zxymq.UserInfo["payload"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Type id handling not implemented for type java.lang.String (by serializer of type com.zxymq.amqp.util.json.JsonMapper$2) (through reference chain: com.zxymq.UserInfo["payload"])

	at org.springframework.data.redis.serializer.Jackson2JsonRedisSerializer.serialize(Jackson2JsonRedisSerializer.java:85)
	at org.springframework.data.redis.core.AbstractOperations.rawHashValue(AbstractOperations.java:171)
	at org.springframework.data.redis.core.DefaultHashOperations.put(DefaultHashOperations.java:168)
	at com.zxymq.amqp.util.redis.RedisUtils.addMap(RedisUtils.java:380)
	at com.zxymq.UserModeSendTest.testRedis(UserModeSendTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Type id handling not implemented for type java.lang.String (by serializer of type com.zxymq.amqp.util.json.JsonMapper$2) (through reference chain: com.zxymq.UserInfo["payload"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:301)
	at com.fasterxml.jackson.databind.SerializerProvider.mappingException(SerializerProvider.java:1096)
	at com.fasterxml.jackson.databind.JsonSerializer.serializeWithType(JsonSerializer.java:160)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:674)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:569)
	at com.fasterxml.jackson.databind.ser.impl.TypeWrappedSerializer.serialize(TypeWrappedSerializer.java:32)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3631)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3022)
	at org.springframework.data.redis.serializer.Jackson2JsonRedisSerializer.serialize(Jackson2JsonRedisSerializer.java:83)
	... 32 more

**Comment by wfm0105** [comment]
已经解决，是因为内部类的原因，吧内部类单独提出来就没有问题

**Comment by vvsuperman** [comment]
demo已全部完成，参考 https://github.com/vvsuperman/coolmq-spring-cloud-demo

**Comment by vvsuperman** [comment]
@wfm0105 因为redis序列化的原因，参考新提交config里的redis配置
